.TH sfm 1 sfm\-VERSION
.SH NAME
sfm \- simple
.SH SYNOPSIS
.B sfm
.RB [ \-hv ]
.SH DESCRIPTION
sfm is a simple
.P
.SH OPTIONS
.TP
.B \-h
prints usage help.
.TP
.B \-v
print version.
.SH USAGE
.TP
.B sfm
.SH CUSTOMIZATION
sfm is customized by creating a custom config.h and (re)compiling the source
code. This keeps it fast, secure and simple.
.SH AUTHORS
Hassan Afify <hassan at afify dot dev>
