.TH sfm 1 sfm\-VERSION
.SH NAME
sfm \- simple file manager
.SH SYNOPSIS
.B sfm
.RB [ \-v ]
.SH DESCRIPTION
sfm is a simple file manager for unix-like systems based on termbox.
dual panes, bottom statusbar, bookmarks, open files by extention, vim-like key bindings as default configuration. current directory is left pane default directory.
.P
.SH OPTIONS
.TP
.B \-v
print version.
.SH USAGE
.TP
.B q
quit
.TP
.B h
back
.TP
.B j
down
.TP
.B k
up
.TP
.B l
open dir | file
.TP
.B g
top
.TP
.B G
bottom
.TP
.B ctrl+u
scroll up
.TP
.B ctrl+d
scroll down
.TP
.B n
create new file if not exists (perm = 600)
.TP
.B N
create new directory if not exists
.TP
.B D
delete file | directory recursively
.TP
.B /
start filter
.TP
.B ENTER
find filter
.TP
.B ESC
exit filter
.TP
.B SPACE
switch pane
.SH CUSTOMIZATION
sfm is customized by creating a custom
.IR config.h
and (re)compiling the source
code. This keeps it fast, secure and simple.
.SH ENVIRONMENT
.TP
.B EDITOR
used to open any file with unconfigured extention. use vi(1) if not set.
.TP
.B HOME
right pane default directory, go to / if not set.
.SH AUTHORS
Hassan Afify <hassan at afify dot dev>
