name: Clang Format Check

on:
  push:
    branches:
      - term
  pull_request:
    branches:
      - term

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      - name: Run clang-format
        run: |
          clang-format -i sfm.c sfm.h

      - name: Check for formatting changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git diff --exit-code || (git add sfm.c sfm.h && git commit -m "Apply clang-format changes" && git push)
